version: '3'
services:
  frontend:
    build:
      context: frontend
    tty: true
    stdin_open: true
    command: npm run dev
    volumes:
      - ./frontend/src/:/app/src
    working_dir: /app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build:
      context: backend
    tty: true
    stdin_open: true
    command: ['bash', '-c', 'npm run db:reset && npm run dev']
    restart: always
    volumes:
      - ./backend/src/:/app/src
    working_dir: /app
    ports:
      - '3001:3001'
    depends_on:
      - database
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: emepar_db
    networks:
      - "emepar_net"
  database:
    container_name: mysql
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - "emepar_net"
networks:
  emepar_net:
    driver: bridge
